[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn --chdir backend app:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
